INSERT INTO GIFT_CATALOG (GIFT_ID, MIN_PURCHASE, GIFTS)
VALUES (1, 100, GIFT_TABLE('Stickers', 'Pen Set' ));

INSERT INTO GIFT_CATALOG (GIFT_ID, MIN_PURCHASE, GIFTS)
VALUES (2, 1000, GIFT_TABLE('Teddy Bear', 'Mug', 'Perfume Sample'));

INSERT INTO GIFT_CATALOG (GIFT_ID, MIN_PURCHASE, GIFTS)
VALUES (3, 10000, GIFT_TABLE('Backpack', 'Thermos Bottle', 'Chocolate Collection'));